In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel('E:\\Book3.xlsx')
df

,ID,Spending ability,Personality Type,Potential to shift from preference 1(in terms of price for the same product) (%),Distance Factor with respect to hostel location (out of 10),Potential to shift from preference 1(in terms of quality for the same product)(%),New customer,Old Customer,Foodie Index ( tendenc to try out new things),Winniability,Food Rating w.r.t. our Product,sum
0,FC0001,Low,100,38,88,56,0,1,40,89,50.0,1550
1,FC0002,Medium,70,62,30,37,0,1,100,54,80.0,1470
2,FC0003,High,100,54,33,49,1,0,70,81,NaN,1710
3,FC0004,Low,80,76,74,53,1,0,80,76,NaN,1515
4,FC0005,Low,100,44,42,61,1,0,60,74,NaN,1480
...,...,...,...,...,...,...,...,...,...,...,...,...
2995,FC2996,High,20,69,96,75,1,0,80,85,NaN,1560
2996,FC2997,Medium,30,32,11,20,0,1,40,52,50.0,1370
2997,FC2998,High,100,58,5,69,0,1,80,45,100.0,1460
2998,FC2999,High,10,70,100,34,0,1,60,49,80.0,1580
2999,FC3000,Low,80,25,47,33,0,1,100,57,60.0,1450

In [3]:
dfx = df

In [4]:
df=dfx.sort_values(by ='sum', ascending=True).head(1800)

In [5]:
df1= df[df['Spending ability']!='Low']
df1

,ID,Spending ability,Personality Type,Potential to shift from preference 1(in terms of price for the same product) (%),Distance Factor with respect to hostel location (out of 10),Potential to shift from preference 1(in terms of quality for the same product)(%),New customer,Old Customer,Foodie Index ( tendenc to try out new things),Winniability,Food Rating w.r.t. our Product,sum
2615,FC2616,High,90,46,27,27,1,0,90,81,NaN,1060
153,FC0154,Medium,40,54,82,57,1,0,100,53,NaN,1060
1529,FC1530,Medium,30,35,40,62,0,1,80,84,40.0,1100
430,FC0431,High,100,76,76,30,1,0,80,37,NaN,1100
2136,FC2137,High,40,47,24,50,1,0,50,63,NaN,1110
...,...,...,...,...,...,...,...,...,...,...,...,...
2057,FC2058,Medium,80,77,37,76,0,1,80,55,50.0,1540
1655,FC1656,Medium,30,49,41,20,1,0,60,50,NaN,1540
1089,FC1090,Medium,90,77,42,65,0,1,60,43,40.0,1540
1090,FC1091,Medium,70,68,48,43,1,0,60,46,NaN,1540
1329,FC1330,High,90,41,81,37,0,1,90,40,30.0,1540

In [6]:
df2 = df1[(df1['Winniability']>=50) & (df['Personality Type']>=40)]

C:\Users\nites\AppData\Local\Temp/ipykernel_10144/1660283198.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df1[(df1['Winniability']>=50) & (df['Personality Type']>=40)]

In [7]:
df2

,ID,Spending ability,Personality Type,Potential to shift from preference 1(in terms of price for the same product) (%),Distance Factor with respect to hostel location (out of 10),Potential to shift from preference 1(in terms of quality for the same product)(%),New customer,Old Customer,Foodie Index ( tendenc to try out new things),Winniability,Food Rating w.r.t. our Product,sum
2615,FC2616,High,90,46,27,27,1,0,90,81,NaN,1060
153,FC0154,Medium,40,54,82,57,1,0,100,53,NaN,1060
2136,FC2137,High,40,47,24,50,1,0,50,63,NaN,1110
598,FC0599,High,70,76,78,70,0,1,80,88,50.0,1160
1907,FC1908,High,100,71,60,45,0,1,70,90,80.0,1160
...,...,...,...,...,...,...,...,...,...,...,...,...
2991,FC2992,High,90,35,49,73,1,0,100,80,NaN,1540
1411,FC1412,Medium,60,38,93,33,1,0,40,74,NaN,1540
2726,FC2727,Medium,70,46,86,50,1,0,40,64,NaN,1540
2407,FC2408,High,70,66,47,20,1,0,80,67,NaN,1540
2057,FC2058,Medium,80,77,37,76,0,1,80,55,50.0,1540

In [8]:
dfp = df2[df2['Distance Factor with respect to hostel location (out of 10)']<=60]

In [9]:
dfp

,ID,Spending ability,Personality Type,Potential to shift from preference 1(in terms of price for the same product) (%),Distance Factor with respect to hostel location (out of 10),Potential to shift from preference 1(in terms of quality for the same product)(%),New customer,Old Customer,Foodie Index ( tendenc to try out new things),Winniability,Food Rating w.r.t. our Product,sum
2615,FC2616,High,90,46,27,27,1,0,90,81,NaN,1060
2136,FC2137,High,40,47,24,50,1,0,50,63,NaN,1110
1907,FC1908,High,100,71,60,45,0,1,70,90,80.0,1160
1649,FC1650,Medium,100,44,24,65,1,0,40,83,NaN,1200
2980,FC2981,Medium,60,21,19,62,1,0,50,89,NaN,1210
...,...,...,...,...,...,...,...,...,...,...,...,...
246,FC0247,Medium,50,78,53,24,1,0,40,56,NaN,1540
1020,FC1021,Medium,40,80,20,79,1,0,40,77,NaN,1540
2991,FC2992,High,90,35,49,73,1,0,100,80,NaN,1540
2407,FC2408,High,70,66,47,20,1,0,80,67,NaN,1540
2057,FC2058,Medium,80,77,37,76,0,1,80,55,50.0,1540

In [10]:
dfp= dfp[dfp['Potential to shift from preference 1(in terms of quality for the same product)(%)']>30]

In [11]:
dfp = dfp[dfp['Potential to shift from preference 1(in terms of price for the same product) (%)']>40]

In [12]:
dfp

,ID,Spending ability,Personality Type,Potential to shift from preference 1(in terms of price for the same product) (%),Distance Factor with respect to hostel location (out of 10),Potential to shift from preference 1(in terms of quality for the same product)(%),New customer,Old Customer,Foodie Index ( tendenc to try out new things),Winniability,Food Rating w.r.t. our Product,sum
2136,FC2137,High,40,47,24,50,1,0,50,63,NaN,1110
1907,FC1908,High,100,71,60,45,0,1,70,90,80.0,1160
1649,FC1650,Medium,100,44,24,65,1,0,40,83,NaN,1200
96,FC0097,High,70,73,26,59,0,1,70,80,90.0,1210
1849,FC1850,Medium,70,60,10,62,0,1,90,83,100.0,1220
...,...,...,...,...,...,...,...,...,...,...,...,...
785,FC0786,Medium,50,71,43,65,1,0,50,81,NaN,1540
2012,FC2013,High,60,42,3,61,0,1,50,73,70.0,1540
1051,FC1052,Medium,40,54,11,67,0,1,70,72,40.0,1540
1020,FC1021,Medium,40,80,20,79,1,0,40,77,NaN,1540
2057,FC2058,Medium,80,77,37,76,0,1,80,55,50.0,1540

In [13]:
dfp

,ID,Spending ability,Personality Type,Potential to shift from preference 1(in terms of price for the same product) (%),Distance Factor with respect to hostel location (out of 10),Potential to shift from preference 1(in terms of quality for the same product)(%),New customer,Old Customer,Foodie Index ( tendenc to try out new things),Winniability,Food Rating w.r.t. our Product,sum
2136,FC2137,High,40,47,24,50,1,0,50,63,NaN,1110
1907,FC1908,High,100,71,60,45,0,1,70,90,80.0,1160
1649,FC1650,Medium,100,44,24,65,1,0,40,83,NaN,1200
96,FC0097,High,70,73,26,59,0,1,70,80,90.0,1210
1849,FC1850,Medium,70,60,10,62,0,1,90,83,100.0,1220
...,...,...,...,...,...,...,...,...,...,...,...,...
785,FC0786,Medium,50,71,43,65,1,0,50,81,NaN,1540
2012,FC2013,High,60,42,3,61,0,1,50,73,70.0,1540
1051,FC1052,Medium,40,54,11,67,0,1,70,72,40.0,1540
1020,FC1021,Medium,40,80,20,79,1,0,40,77,NaN,1540
2057,FC2058,Medium,80,77,37,76,0,1,80,55,50.0,1540

In [14]:
dfp[dfp['Spending ability']=='High']

,ID,Spending ability,Personality Type,Potential to shift from preference 1(in terms of price for the same product) (%),Distance Factor with respect to hostel location (out of 10),Potential to shift from preference 1(in terms of quality for the same product)(%),New customer,Old Customer,Foodie Index ( tendenc to try out new things),Winniability,Food Rating w.r.t. our Product,sum
2136,FC2137,High,40,47,24,50,1,0,50,63,NaN,1110
1907,FC1908,High,100,71,60,45,0,1,70,90,80.0,1160
96,FC0097,High,70,73,26,59,0,1,70,80,90.0,1210
315,FC0316,High,90,78,2,43,0,1,90,55,90.0,1270
870,FC0871,High,40,42,43,68,1,0,80,60,NaN,1270
...,...,...,...,...,...,...,...,...,...,...,...,...
2430,FC2431,High,60,80,33,65,0,1,90,86,80.0,1530
2709,FC2710,High,100,64,24,67,0,1,70,58,40.0,1530
237,FC0238,High,70,70,23,77,0,1,70,61,90.0,1530
2835,FC2836,High,50,66,8,58,0,1,70,53,80.0,1530
2012,FC2013,High,60,42,3,61,0,1,50,73,70.0,1540